# defaults file for zabbix-agent

zabbix_version: 4.2
zabbix_version_patch: 0
zabbix_repo: zabbix
zabbix_agent_package: zabbix-agent
zabbix_agent_package_state: present
zabbix_agent_server: pxzb01,hxzb01
zabbix_agent_serveractive: pxzb01,hxzb01
zabbix_selinux: False

# Zabbix role related vars
zabbix_install_pip_packages: true
zabbix_apt_force_apt_get: yes
zabbix_apt_install_recommends: no

# Override Ansible specific facts
zabbix_agent_distribution_major_version: "{{ ansible_distribution_major_version }}"
zabbix_agent_distribution_release: "{{ ansible_distribution_release }}"
zabbix_agent_os_family: "{{ ansible_os_family }}"


# Zabbix API stuff
zabbix_url: "https://mis.energia.org.br/zabbix/"
zabbix_api_user: apizabbix
zabbix_api_pass: "Prod%23819"
zabbix_api_create_hostgroup: False
zabbix_api_create_hosts: True
zabbix_create_hostgroup: present  # or absent
zabbix_create_host: present       # or absent
zabbix_update_host: yes
zabbix_host_status: enabled       # or disabled
zabbix_proxy: null
zabbix_inventory_mode: disabled
zabbix_useuip: 1
zabbix_host_groups:
  - HostGroup_Infra_N1
zabbix_link_templates:
  - Template_Infra_Linux

zabbix_agent_interfaces:
  - type: 1
    main: 1
    useip: "{{ zabbix_useuip }}"
    ip: "{{ zabbix_agent_ip }}"
    dns: "{{ ansible_fqdn }}"
    port: "{{ zabbix_agent_listenport }}"

zabbix_agent_firewall_enable: true
zabbix_agent_firewalld_enable: true
zabbix_agent_firewalld_source: "{{ zabbix_agent_server }}"
zabbix_agent_firewall_action: insert
zabbix_agent_firewall_chain: INPUT
zabbix_agent_firewalld_zone: public
# Zabbix configuration variables
zabbix_agent_pidfile: /var/run/zabbix/zabbix_agentd.pid
zabbix_agent_logfile: /var/log/zabbix/zabbix_agentd.log
zabbix_agent_logfilesize: 100
zabbix_agent_debuglevel: 3
zabbix_agent_sourceip:
zabbix_agent_enableremotecommands: 1
zabbix_agent_logremotecommands: 1
zabbix_agent_listenport: 10050
zabbix_agent_listenport_fw: "10050/tcp"
zabbix_agent_jmx_listenport:
zabbix_agent_listeninterface:
zabbix_agent_listenip: 0.0.0.0
zabbix_agent_startagents: 3
#zabbix_agent_hostname: "{{ inventory_hostname }}"
zabbix_agent_hostname: "{{ ansible_hostname }}"
zabbix_agent_hostnameitem:
zabbix_agent_hostmetadata:
zabbix_agent_hostmetadataitem:
zabbix_agent_refreshactivechecks: 120
zabbix_agent_buffersend: 5
zabbix_agent_buffersize: 100
zabbix_agent_maxlinespersecond: 100
zabbix_agent_allowroot: 1
zabbix_agent_zabbix_alias:
zabbix_agent_timeout: 30
zabbix_agent_include: /etc/zabbix/zabbix_agentd.d
zabbix_agent_unsafeuserparameters: 0
zabbix_agent_userparameter:
zabbix_agent_userparameters: []
zabbix_agent_custom_scripts: false
zabbix_agent_loadmodulepath: ${libdir}/modules
zabbix_agent_loadmodule:
zabbix_agent_become_on_localhost: True
# Zabbix Agent Docker facts
zabbix_agent_docker: False
zabbix_agent_docker_state: started
zabbix_agent_docker_name: zabbix-agent
zabbix_agent_docker_image: "zabbix/zabbix-agent"
zabbix_agent_docker_image_tag: "ubuntu-{{ zabbix_version }}.{{ zabbix_version_patch }}"
zabbix_agent_docker_user_gid: 101
zabbix_agent_docker_user_uid: 101
zabbix_agent_docker_network_mode: host
zabbix_agent_docker_restart_policy: unless-stopped
zabbix_agent_docker_privileged: False
zabbix_agent_docker_ports:
  - 10050:10050
zabbix_agent_docker_security_opts:
  - apparmor:unconfined
zabbix_agent_docker_volumes:
  - /etc/zabbix/zabbix_agentd.d:{{ zabbix_agent_include }}
  - /:/hostfs:ro
  - /etc:/hostfs/etc:ro
  - /proc:/hostfs/proc:ro
  - /sys:/hostfs/sys:ro
  - /var/run:/var/run
zabbix_agent_docker_env:
  ZBX_HOSTNAME: "{{ zabbix_agent_hostname }}"
  ZBX_SERVER_HOST: "{{ zabbix_agent_server }}"
  ZBX_PASSIVE_ALLOW: "{{ zabbix_agent_serverpassive_allow | default(omit) }}"
  ZBX_PASSIVESERVERS: "{{ zabbix_agent_serverpassive | default(omit) }}"
  ZBX_ACTIVE_ALLOW: "{{ zabbix_agent_serveractive_allow | default(omit) }}"
  ZBX_LOADMODULE: "{{ zabbix_agent_loadmodule | default(omit) }}"
  ZBX_DEBUGLEVEL: '{{ zabbix_agent_debuglevel }}'
  ZBX_TIMEOUT: '{{ zabbix_agent_timeout }}'
  ZBX_SOURCEIP: "{{ zabbix_agent_sourceip | default(omit) }}"
  ZBX_ENABLEREMOTECOMMANDS: "{{ zabbix_agent_enableremotecommands | default(omit) }}"
  ZBX_LOGREMOTECOMMANDS: "{{ zabbix_agent_logremotecommands | default(omit) }}"
  ZBX_STARTAGENTS: "{{ zabbix_agent_startagents | default(omit) }}"
  ZBX_HOSTNAMEITEM: "{{ zabbix_agent_hostnameitem | default(omit) }}"
  ZBX_METADATA: "{{ zabbix_agent_hostmetadata | default(omit) }}"
  ZBX_METADATAITEM: "{{ zabbix_agent_hostmetadataitem | default(omit) }}"
  ZBX_REFRESHACTIVECHECKS: "{{ zabbix_agent_refreshactivechecks | default(omit) }}"
  ZBX_BUFFERSEND: "{{ zabbix_agent_buffersend | default(omit) }}"
  ZBX_BUFFERSIZE: "{{ zabbix_agent_buffersize | default(omit) }}"
  ZBX_MAXLINESPERSECOND: "{{ zabbix_agent_maxlinespersecond | default(omit) }}"
  ZBX_LISTENIP: "{{ zabbix_agent_listenip }}"
  ZBX_UNSAFEUSERPARAMETERS: "{{ zabbix_agent_unsafeuserparameters | default(omit) }}"
  ZBX_TLSCONNECT: "{{ zabbix_agent_tlsconnect | default(omit) }}"
  ZBX_TLSACCEPT: "{{ zabbix_agent_tlsaccept | default(omit) }}"
  ZBX_TLSCAFILE: "{{ zabbix_agent_tlscafile | default(omit) }}"
  ZBX_TLSCRLFILE: "{{ zabbix_agent_tlscrlfile | default(omit) }}"
  ZBX_TLSSERVERCERTISSUER: "{{ zabbix_agent_tlsservercertissuer | default(omit) }}"
  ZBX_TLSSERVERCERTSUBJECT: "{{ zabbix_agent_tlsservercertsubject | default(omit) }}"
  ZBX_TLSCERTFILE: "{{ zabbix_agent_tlscertfile | default(omit) }}"
  ZBX_TLSKEYFILE: "{{ zabbix_agent_tlskeyfile | default(omit) }}"
  ZBX_TLSPSKIDENTITY: "{{ zabbix_agent_tlspskidentity | default(omit) }}"

