---

#- name: "Instala libselinux"
#  yum:
#    name: libselinux-python 
#    state: present

- name: "Desabilitando SeLinux"
  selinux:
    policy: targeted
    state: disabled

- name: "Configurando IPTables (zabbix_agent_listenport)"
  when: ansible_os_family == "RedHat" and ansible_distribution_major_version == '6'
  iptables:
    action: "{{ zabbix_agent_firewall_action }}"
    destination_port: "{{ zabbix_agent_listenport }}"
    source: "{{ zabbix_agent_firewall_source | default(omit) }}"
    protocol: tcp
    chain: "{{ zabbix_agent_firewall_chain }}"
    jump: ACCEPT
  become: yes
  when: zabbix_agent_firewall_enable | bool

- name: "Configura firewalld (zabbix_agent_listenport)"
  when: ansible_os_family == "RedHat" and ansible_distribution_major_version == '7'
  firewalld:
    zone: "{{ zabbix_agent_firewalld_zone }}"
    port: "{{ zabbix_agent_listenport_fw }}"
    permanent: true
    state: enabled
  when: zabbix_agent_firewalld_enable | bool
  notify:
    - firewalld-reload
  tags: zabbix_agent_firewalld_enable


- name: "Check RHSM release 6 para copiar o pacote correto"
  when: ansible_os_family == "RedHat" and ansible_distribution_major_version == '6'
  copy:
    src: zabbix-agent-4.2.3-2.el6.x86_64.rpm
    dest: /tmp/zabbix-agent-4.2.3-2.el6.x86_64.rpm
    owner: root
    group: root
    mode: 0644
  become: yes

- name: "Instalando zabbix-agent RPM versão 6"
  when: ansible_os_family == "RedHat" and ansible_distribution_major_version == '6'
  yum:
    name: /tmp/zabbix-agent-4.2.3-2.el6.x86_64.rpm
    state: present
  become: yes



- name: "Check RHSM release 7 version to install package"
  when: ansible_os_family == "RedHat" and ansible_distribution_major_version == '7'
  copy:
    src: zabbix-agent-4.2.3-1.el7.x86_64.rpm
    dest: /tmp/zabbix-agent-4.2.3-1.el7.x86_64.rpm
    owner: root
    group: root
    mode: 0644
  become: yes


- name: "Instalando zabbix-agent RPM versão 7"
  when: ansible_os_family == "RedHat" and ansible_distribution_major_version == '7'
  yum:
    name: /tmp/zabbix-agent-4.2.3-1.el7.x86_64.rpm
    state: present
  become: yes

- name: "Copiando arquivos userparameters_iostat"
  when: ansible_os_family == "RedHat" and ansible_distribution_major_version == '7'
  copy:
    src: userparameter_iostat.conf
    dest: /etc/zabbix/zabbix_agentd.d/userparameter_iostat.conf
    owner: root
    group: root
    mode: 0644
  become: yes


- name: "Copiando .conf para o diretorio /etc/zabbix"
  template:
    src: zabbix_agentd.conf
    dest: /etc/zabbix/zabbix_agentd.conf
    owner: root
    group: root
    mode: 0644
    backup: yes
  notify:
    - restart zabbix-agent
  become: yes
  when:
    - not (zabbix_agent_docker | bool)
  tags:
    - zabbix-agent
    - config
    - init

- name: "Definindo o endereço IP no FACT para zabbix_agent_ip"
  set_fact:
    zabbix_agent_ip: "{{ hostvars[inventory_hostname]['ansible_default_ipv4'].address }}"
  when:
    - zabbix_agent_ip is not defined
    - "'ansible_default_ipv4' in hostvars[inventory_hostname]"
  become: yes

- name: "Definindo o primeiro endereço IP privado para zabbix_agent_ip"
  set_fact:
    zabbix_agent_ip: "{{ ansible_all_ipv4_addresses | ipaddr('private') | first }}"
  when:
    - zabbix_agent_ip is not defined
    - total_private_ip_addresses is defined
    - total_private_ip_addresses != '0'
  become: yes

- name: "Falha agent_listeninterface especificada inválida"
  fail:
    msg: "The specified network interface does not exist"
  when:
    - zabbix_agent_listeninterface
    - (zabbix_agent_listeninterface not in ansible_all_ipv4_addresses)
  tags:
    - zabbix-agent
    - config
  become: yes

- name: "Definir IP interface para listen caso especificado"
  set_fact:
    network_interface: ansible_{{ zabbix_agent_listeninterface }}
  when:
    - zabbix_agent_listeninterface
    - not zabbix_agent_listenip
  become: yes

- name: "Obtenha o IP do agent_listeninterface quando nenhum agent_listenip for especificado"
  set_fact:
    zabbix_agent_listenip: "{{ hostvars[inventory_hostname][network_interface]['ipv4'].address | default('0.0.0.0') }}"
    zabbix_agent_ip: "{{ hostvars[inventory_hostname][network_interface]['ipv4'].address | default('0.0.0.0') }}"
  when:
    - zabbix_agent_listeninterface
    - not zabbix_agent_listenip
  tags:
    - zabbix-agent
    - config
    - api
  become: yes

- name: "Agent_listenip padrão para todos quando não especificado"
  set_fact:
    zabbix_agent_listenip: '0.0.0.0'
  when:
    - not zabbix_agent_listenip
  tags:
    - zabbix-agent
    - config
  become: yes

- name: "Falha agent_listenip especificado inválido"
  fail:
    msg: "The agent_listenip does not exist"
  when:
    - zabbix_agent_listenip != '0.0.0.0'
    - zabbix_agent_listenip != '127.0.0.1'
    - (zabbix_agent_listenip not in ansible_all_ipv4_addresses)
  tags:
    - zabbix-agent
    - config
  become: yes

- name: "Installing the Zabbix-api package on localhost"
  pip:
    name: zabbix-api
    state: present
  register: zabbix_api_package_installed
  until: zabbix_api_package_installed is succeeded
  delegate_to: localhost
  become: "{{ zabbix_agent_become_on_localhost }}"
  when:
    - zabbix_install_pip_packages | bool
    - (zabbix_api_create_hostgroup | bool) or (zabbix_api_create_hosts | bool)

- name: "Cria um novo host ou atualize as informações de um host existente"
#  hosts: pxzb01
  zabbix_host:
    server_url: "{{ zabbix_url }}"
    login_user: "{{ zabbix_api_user }}"
    login_password: "{{ zabbix_api_pass }}"
    host_name: "{{ zabbix_agent_hostname }}"
    host_groups: "{{ zabbix_host_groups }}"
    link_templates: "{{ zabbix_link_templates }}"
    status: "{{ zabbix_host_status }}"
    state: "{{ zabbix_create_host }}"
    force: "{{ zabbix_update_host }}"
#    proxy: "{{ zabbix_proxy }}"
    inventory_mode: "{{ zabbix_inventory_mode }}"
    interfaces: "{{ zabbix_agent_interfaces }}"
    visible_name: "{{ zabbix_visible_hostname|default(zabbix_agent_hostname) }}"
  when:
    - zabbix_api_create_hosts | bool
  delegate_to: localhost
  become: no
  changed_when: false
  tags:
    - api

- name: "Including userparameters"
  include: "userparameter.yml"
  when: zabbix_agent_userparameters|length > 0
  tags:
    - zabbix-agent
    - userparameter
  become: yes
                                
